FILES = main_pre.js time.js elabel.js soundmanager.js communication.js communicationmanager.js gameobject.js collisionmanager.js collider.js player.js gun.js bullet.js enemymanager.js enemy.js enemy_dog.js level.js backgroundlayer.js scene_title.js scene_battle.js scene_battle_menu.js main_post.js
OUTPUT_NAME = game-build.js

${OUTPUT_NAME} : ${FILES}
		@@echo "Build game js files(${FILES}) to ${OUTPUT_NAME}..."
		@@cat ${FILES} > ${OUTPUT_NAME}
		@@echo "Finished Build."
